version: "3.1"
services: 

  apache: 
    restart: always
    image: tutum/apache-php
    container_name: apache
    volumes: 
      - ./www:/app
      - ./configs/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
      - ./configs/apache:/etc/apache2/sites-enabled
    links: 
      - php
      - mariadb
    ports: 
      - "80:80"

  php:
    restart: always
    image: php:7.0
    container_name: php7
    links: 
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:3306"

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin:latest
    container_name: admin
    links: 
      - mariadb
    environment: 
      PMA_HOST: mariadb
    ports:
      - "8082:80"